name: Go
on: [push]
jobs:

  build:
    name: Build
    strategy:
      matrix:
        go: ['1.13']
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      id: checkout

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
      id: go

    - uses: actions/cache@v1
      with:
        path: ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Build
      run: go build -v .
